"""
nirvana10k: Analysis of UV-Vis spectroscopy data from Nirvana tool measurements

This package provides tools for processing and analyzing UV-Vis spectroscopy data
from HDF5 files generated by the Nirvana instrument.
"""

from .read.h5tosample import h5_to_samples
from .measurements.uvvis import NirvanaUVVis

__version__ = "0.1.0"
__author__ = "roncofaber"

__all__ = ["h5_to_samples", "NirvanaUVVis"]